#!/bin/bash
#
# ARG_POSITIONAL_INF([file],[3 xvg files]))
# ARG_OPTIONAL_SINGLE([prefix],[p],[add prefix for the file output])
# ARG_OPTIONAL_BOOLEAN([sasa], , [pdb combine with sasa data on])
# ARG_OPTIONAL_SINGLE([ref],[r],[in case of --sasa on, add pdb reference pdb file ])
# ARG_OPTIONAL_BOOLEAN([xvg], , [enables xvg files as input])
# ARG_HELP([The general script's help msg])
# ARG_OPTIONAL_REPEATED([include],[I],[Directory for temporary folders],['/tmp'])

# ARGBASH_GO

# [ <-- needed because of Argbash

#### Var ####
SECONDS=0
TEMP="$_arg_include"
WPATH="$(pwd)"
touch $TEMP/.n
file1="${_arg_file[0]}"
file2="${_arg_file[1]}"
file3="${_arg_file[2]}"
files="${_arg_file[*]}"

### Functions ###
start () {
version="sasaMeanEr_v1.0"
if [ -z "$file1" ]; then
  echo ""
  echo "$version"
  echo ""
  echo "No Input... -> `basename $0` -h for help"
  echo ""
  exit 0
fi
}

intro () {
format="|%-10s|%-69.69s%s |\n"
empty="|%-81.81s%s|\n"
bend="+%-81.81s%s+\n"
bar="| %-72s%8s|\r"
barend="| %-72s%8s|\n"
minus="-----------" #10

pro11="############" 
pro33="$pro11$pro11"
pro66="$pro33$pro33" 
pro100="$pro33$pro33$pro33"

printf "$bend" "$minus$minus$minus$minus$minus$minus$minus$minus"
printf "$empty" "$minus$minus$minus $version $minus$minus$minus"
printf "$bend" "$minus$minus$minus$minus$minus$minus$minus$minus"
printf "$format" " files" " ${_arg_file[*]}"
printf "$format" ""
printf "$format" " --prefix" " $_arg_prefix"
printf "$format" ""
printf "$format" " --pdb" " $_arg_sasa"
printf "$format" ""
printf "$format" " --ref" " $_arg_ref"
printf "$format" ""
printf "$format" " --xvg" " $_arg_xvg"
printf "$format" ""
printf "$format" " temp dir" " $_arg_include"
printf "$bend" "$minus$minus$minus$minus$minus$minus$minus$minus"
}

timeNeed () {
ELAPSED="$(($SECONDS / 3600))hrs $((($SECONDS / 60) % 60))min $(($SECONDS % 60))sec"
printf "|%-20s%61s|\n" " finished within..." "$ELAPSED"
}

getPdbCoord () {
cat $_arg_ref | grep "ATOM" | awk 'BEGIN{FIELDWIDTHS="60"}{print $1}' >$TEMP/.expdb
}

getSasa () {
for i in ${_arg_file[*]};do
    paste $i | grep -v ^# | grep -v @ | awk {'print $2'} >$TEMP/.ex$i
done
files=$TEMP/.ex*.xvg
file1=$TEMP/.ex*1*.xvg
file2=$TEMP/.ex*2*.xvg
file3=$TEMP/.ex*3*.xvg
}

getXvg () {
for i in ${_arg_file[*]};do
    paste $i | grep -v ^# | grep -v @ | awk {'print $2'} >$TEMP/.ex$i
done
files=$TEMP/.ex*.xvg
file1=$TEMP/.ex*1*.xvg
file2=$TEMP/.ex*2*.xvg
file3=$TEMP/.ex*3*.xvg
}

getLines () {
lineNr=$(wc -l $file1 | awk {'print $1'})
for ((i=1;i<=lineNr;i++));do
    echo $i
done
}

alignRight () {
cat $TEMP/.aver | tsv-pretty | awk 'BEGIN{FIELDWIDTHS="7"}{print $1}' >$TEMP/.ave
cat $TEMP/.err | tsv-pretty >$TEMP/.er
}

calc () {
FILE="$TEMP/.temp1"
FILELINES=`cat $FILE | tr -d "[:blank:]"`
for line in $FILELINES ; do
    echo "scale=5; $line" | bc
done
}

callAver () {
paste -d "(++)/3" $TEMP/.n $files $TEMP/.n $TEMP/.n $TEMP/.n
}

callErr () {
paste -d "(-)^2" $TEMP/.n $file1 $TEMP/.aver $TEMP/.n $TEMP/.n $TEMP/.n >$TEMP/.v1
paste -d "(-)^2" $TEMP/.n $file2 $TEMP/.aver $TEMP/.n $TEMP/.n $TEMP/.n >$TEMP/.v2
paste -d "(-)^2" $TEMP/.n $file3 $TEMP/.aver $TEMP/.n $TEMP/.n $TEMP/.n >$TEMP/.v3
paste -d "(++)/3" $TEMP/.n $TEMP/.v1 $TEMP/.v2 $TEMP/.v3 $TEMP/.n $TEMP/.n $TEMP/.n >$TEMP/.v4
paste -d "sqrt()" $TEMP/.n $TEMP/.n $TEMP/.n $TEMP/.n $TEMP/.n $TEMP/.v4 $TEMP/.n
}

copyBackMeanEr () {
paste $TEMP/.nr $TEMP/.ave $TEMP/.er >$TEMP/.averErr
cp $TEMP/.averErr $WPATH/meanErr$_arg_prefix.dat
}

copyBackStructure () {
paste $TEMP/.nr $TEMP/.ave $TEMP/.er >$TEMP/.averErr
cp $TEMP/.averErr $WPATH/meanErrSasa$_arg_prefix.dat
paste -d "" $TEMP/.expdb $TEMP/.ave >$TEMP/.expdbout
cp $TEMP/.expdbout $WPATH/meanSasa$_arg_prefix.pdb
}

cleanUp () {
rm -r $TEMP/.temp1 $TEMP/.v? $TEMP/.err $TEMP/.er $TEMP/.aver $TEMP/.ave $TEMP/.n $TEMP/.nr $TEMP/.ex*.pdb $TEMP/.expdb $TEMP/.expdbout $TEMP/.averErr $TEMP/.ex*.xvg >/dev/null 2>/dev/null
}

#### Scriptfunction ####
#### PDB 
#### Part 1 - get data
pdbRun1 () {
getPdbCoord
getSasa
getLines >$TEMP/.nr
callAver >$TEMP/.temp1
calc >$TEMP/.aver
}
#### Part 2 - process data
pdbRun2 () {
callErr >$TEMP/.temp1
calc >$TEMP/.err
alignRight
}
#### Part 3 - copy back und cleanup
pdbRun3 () {
copyBackStructure
}

#### Xvg
#### Part 1 - get data
xvgRun1 () {
getXvg
getLines >$TEMP/.nr
callAver >$TEMP/.temp1
calc >$TEMP/.aver
}
#### Part 2 - process data
xvgRun2 () {
callErr >$TEMP/.temp1
calc >$TEMP/.err
alignRight
}
#### Part 3 - copy back und cleanup
xvgRun3 () {
copyBackMeanEr
}

#### printf
p0 () {
printf "$empty" " running..."
printf "$bar" " " "|   0% "
sleep 1s
}
p33 () {
printf "$bar" "$pro33" "|  33% "
sleep 1s
}
p66 () {
printf "$bar" "$pro66" "|  66% "
sleep 1s
}
p100 () {
printf "$barend" "$pro100" "| 100% "
sleep 1s
}

#### pdbRun
pdbRun () {
    pdbRun1
    p33
    pdbRun2
    p66
    pdbRun3
}
#### xvgRun
xvgRun () {
    xvgRun1
    p33
    xvgRun2
    p66
    xvgRun3
}
#### Script ####
start
intro
p0
if [ $_arg_sasa = "on" ] && [ $_arg_xvg = "on" ]; then
    printf "$empty" " both --pdb and --xvg are on -> not allowed..."
elif [ $_arg_xvg = "on" ]; then
    xvgRun
else
    pdbRun
fi
cleanUp
p100
timeNeed
printf "$bend" "$minus$minus$minus$minus$minus$minus$minus$minus"

# ] <-- needed because of Argbash
